language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: HT62UgRxVGDi0ZHZGzVYvwOCDux9wCyzkhcZXvWpiEWTAfBip51HQQ9pSs/j7jt0Jbc9u7qVNBh4BlULKdzM+zD5zY3f8L0jMiUbR1Nq+jp68RUzpGMPnrRWxzr9M2suidwstVNcyIPoBpjO7hYsmH980N9rSUkY3LyU/GxCIXZ6dGiVwVm20ZzGvQQ2yj7TPmiTdv1TKGV6nh5LHFL8YOUw/ro+KJwc6rUS+NNWeQqwvh+12kKvR5RznarQczcEse6f16Kf/gp2gQdrETQqLCUo+3C5YeIZzTDaoAsEgaJIeOHfyfYjeAv4SFrNDoDmWw/hucRijdAyBd4Ohvtg0ZAclKQUD09h9DHmoIpgBJMCs+y4Yml47zIUuF+An9uZ5hzFP3CuqbKX5sa9P3ZMa5ju2sxHeuW2XoqCzVjIjDZx/Y6QN9LlX5iw1aq7BE3iWqVTRHlgmFdbu4Vg3EDevga0B+0OPS2ZHJr3KmCTOGxWXt+4jKFCDKLKQiktrS8dhrAHzkfYip1BXFECXiJssGJfztqiOHN0Wftl3AOVglaWqMD/ZKsd0uF+UmIhVCpd0xoG0HP7mtzBgyAkfC2QW5WyOVjOCmXQ4+G96fgHqfMjRgyuF59qiP/25l876AU+F4UtVnU2qgjTzgwoKTveztpucR/xmHRG+x2Z+VAYGRk=
  file: "target/jmeter-formman-*.jar"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: tilln/jmeter-formman
    tags: true
